from io import BytesIO
import subprocess
import os
import traceback
import logging

from flask import Blueprint, request

from utils.helpers import error, send_file_and_cleanup
from utils.temp_cleanup import TempFileManager, cleanup_file

pptx_pdf_bp = Blueprint("pptx_pdf", __name__)
logger = logging.getLogger(__name__)


@pptx_pdf_bp.route("/convertPptxToPdf", methods=["POST"])
def convert_pptx_to_pdf():
    """
    Convert PPTX to PDF using LibreOffice.

    Guarantees cleanup of temp files on all paths (success, error, timeout)
    via TempFileManager context manager.
    """
    generated_pdf = None

    try:
        if "file" not in request.files:
            return error("No file provided")

        pptx_file = request.files["file"]

        if (
            pptx_file.filename == ""
            or not pptx_file.filename.lower().endswith(".pptx")
        ):
            return error("Please upload a valid .pptx file")

        # Read uploaded file
        pptx_bytes = pptx_file.read()

        # Use TempFileManager to guarantee cleanup of the input PPTX
        with TempFileManager(suffix=".pptx") as tmp_pptx:
            tmp_pptx.write(pptx_bytes)
            temp_pptx = tmp_pptx.name
            output_dir = os.path.dirname(temp_pptx)

            # Convert using LibreOffice
            result = subprocess.run(
                [
                    "libreoffice",
                    "--headless",
                    "--convert-to",
                    "pdf",
                    "--outdir",
                    output_dir,
                    temp_pptx,
                ],
                capture_output=True,
                text=True,
                timeout=60,
            )

            logger.debug(f"LibreOffice STDOUT: {result.stdout}")
            logger.debug(f"LibreOffice STDERR: {result.stderr}")

            if result.returncode != 0:
                return error(
                    f"LibreOffice conversion failed:\n{result.stderr}",
                    500
                )

            # LibreOffice creates: /tmp/xyz.pptx -> /tmp/xyz.pdf
            generated_pdf = os.path.splitext(temp_pptx)[0] + ".pdf"

            if not os.path.exists(generated_pdf):
                return error(
                    "PDF was not generated by LibreOffice",
                    500
                )

            with open(generated_pdf, "rb") as pdf_file:
                pdf_bytes = pdf_file.read()

            if len(pdf_bytes) == 0:
                return error(
                    "Generated PDF is empty",
                    500
                )

            output = BytesIO(pdf_bytes)

            response = send_file_and_cleanup(
                output,
                mimetype="application/pdf",
                as_attachment=True,
                download_name="presentation.pdf"
            )

            # Clean up the generated PDF after sending
            # (TempFileManager already cleaned up the input PPTX)
            cleanup_file(generated_pdf)

            return response

    except subprocess.TimeoutExpired:
        logger.error("Conversion timed out. File may be too large.")
        return error(
            "Conversion timed out. File may be too large.",
            500
        )

    except Exception as e:
        logger.error(f"Conversion failed: {str(e)}")
        traceback.print_exc()
        return error(
            f"Conversion failed: {str(e)}",
            500
        )

    finally:
        # Guarantee cleanup of generated PDF (TempFileManager handles input PPTX)
        cleanup_file(generated_pdf)
